/**
 * Shared product icon surface backed by Phosphor Icons.
 *
 * Keeping application imports stable lets every screen use one coherent,
 * accessible outline family without maintaining handwritten SVG paths.
 */
export {
  Archive as IconArchive,
  ArrowCounterClockwise as IconHistory,
  ArrowSquareOut as IconExternal,
  ArrowsClockwise as IconRefresh,
  Atom as IconAtom,
  Bell as IconBell,
  BookOpenText as IconBook,
  Brain as IconBrain,
  Briefcase as IconWorkspace,
  CaretDown as IconChevronDown,
  CaretLeft as IconChevronLeft,
  CaretRight as IconChevronRight,
  ChatCircleDots as IconChat,
  Check as IconCheck,
  Clock as IconClock,
  Copy as IconCopy,
  Cube as IconBox,
  FileText as IconDocument,
  FloppyDisk as IconSave,
  FolderOpen as IconFolder,
  Gauge as IconGauge,
  GearSix as IconSettings,
  HardDrives as IconServer,
  Key as IconKey,
  Stack as IconLayers,
  Lightning as IconBolt,
  LinkSimple as IconLink,
  List as IconMenu,
  ListChecks as IconChecklist,
  MagnifyingGlass as IconSearch,
  Moon as IconMoon,
  DotsThreeVertical as IconMore,
  PaperPlaneTilt as IconSend,
  Paperclip as IconAttachment,
  PencilSimple as IconEdit,
  Plus as IconPlus,
  ShieldCheck as IconShield,
  Sparkle as IconSparkle,
  Square as IconStop,
  SquaresFour as IconGrid,
  Stethoscope as IconProbe,
  Sun as IconSun,
  Trash as IconTrash,
  UserCircle as IconUser,
  UsersThree as IconUsers,
  Warning as IconAlert,
  X as IconClose,
} from "@phosphor-icons/react";
