/**
 * Shared product icon surface backed by Phosphor Icons.
 *
 * Keeping application imports stable lets every screen use one coherent,
 * accessible outline family without maintaining handwritten SVG paths.
 */
export {
  Archive as IconArchive,
  ArrowClockwise as IconRedo,
  ArrowCounterClockwise as IconHistory,
  ArrowCounterClockwise as IconUndo,
  ArrowSquareOut as IconExternal,
  ArrowsClockwise as IconRefresh,
  ArrowsLeftRight as IconArrowsX,
  ArrowsSplit as IconSplit,
  Atom as IconAtom,
  Bell as IconBell,
  BookOpenText as IconBook,
  Brain as IconBrain,
  Briefcase as IconWorkspace,
  CaretDown as IconChevronDown,
  CaretLeft as IconChevronLeft,
  CaretRight as IconChevronRight,
  ChatCircleDots as IconChat,
  Check as IconCheck,
  Clock as IconClock,
  Cloud as IconCloud,
  Copy as IconCopy,
  Cube as IconBox,
  Eye as IconEye,
  FileText as IconDocument,
  FloppyDisk as IconSave,
  FolderOpen as IconFolder,
  Gauge as IconGauge,
  GearSix as IconSettings,
  GitBranch as IconBranch,
  HardDrives as IconServer,
  Key as IconKey,
  Stack as IconLayers,
  Lightning as IconBolt,
  LinkSimple as IconLink,
  List as IconMenu,
  ListChecks as IconChecklist,
  MagnifyingGlass as IconSearch,
  Moon as IconMoon,
  DotsThreeVertical as IconMore,
  PaperPlaneTilt as IconSend,
  Paperclip as IconAttachment,
  PencilSimple as IconEdit,
  Plugs as IconPlugs,
  Plus as IconPlus,
  ShareNetwork as IconShare,
  ShieldCheck as IconShield,
  Sparkle as IconSparkle,
  Square as IconStop,
  SquaresFour as IconGrid,
  Stethoscope as IconProbe,
  Sun as IconSun,
  Trash as IconTrash,
  TreeStructure as IconTree,
  UserCircle as IconUser,
  UsersThree as IconUsers,
  Warning as IconAlert,
  WifiHigh as IconWifi,
  X as IconClose,
} from "@phosphor-icons/react";
